lastproject/apps/project/urls.py
from django.conf.urls import url
from . import views

app_name = "project"

urlpatterns = [
    url(r'^wishlist$', views.wishlist, name="wishlist"),
    url(r'^additem', views.additem, name="additem"),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^itemadded/(?P<id>\d+)$', views.itemadded, name='itemadded'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
    url(r'^iteminfo/(?P<id>\d+)$', views.iteminfo, name='iteminfo'),
    url(r'^add2wish/(?P<id>\d+)$', views.add2wish, name='add2wish'),
]

lastproject/lastproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^project/', include('apps.project.urls', namespace='project')),
    url(r'^', include('apps.logreg.urls', namespace='logreg'))
]

lastproject/apps/project/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt
from django.db.models import F
from datetime import date
from datetime import datetime
from ..logreg.models import User

class UserManager(models.Manager):

    def GetCurrentUser(self, request):
        print "func GetCurrentUser"
        print (request.session['id'])
        try:
            usrReturn = User.objects.get(id=request.session['id'])
            print "test!! ",User.objects.get(id=request.session['id']).name
            return usrReturn
        except Exception as e:
            print '%s (%s)' % (e.message, type(e))
            return e

    def itemadded(self,data,id):
        error = []
        if len(data['item']) < 3:
            error.append("Item field must be more than 3 characters and cannot be blank!")
        if not error:
            try:
                currentUser = User.objects.get(id=id)
                print 1
                Items.objects.create(user=currentUser,item=data['item'])
                print 2
                return True
            except:
                pass
        else:
            return (False,error)

    def deleteList(self,id):
        print "in delete function - Models"
        objDelete = Items.objects.get(id=id)
        objDelete.delete()
        return True

    def removeList(self,request,id):
        print "in remove function - Models"
        currentUser = self.GetCurrentUser(request)
        item = Items.objects.get(id=id)
        addedwish = AddedWish.objects.get(item=item,name=currentUser.name)
        objDelete = addedwish
        objDelete.delete()
        return True

    def addWish(self,request,id):
        addwish = Items.objects.get(id=id)
        currentUser = self.GetCurrentUser(request)
        print "In addList func - Models, User: ", addwish.user.name
        AddedWish.objects.create(item=addwish,name=currentUser.name)
        return True

class Items(models.Model):
    user = models.ForeignKey(User,related_name="the_user")
    item = models.CharField(max_length=40)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

class AddedWish(models.Model):
    item = models.ForeignKey(Items,related_name="the_item")
    name = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

lastproject/apps/project/views.py
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import User, Items, AddedWish
from datetime import datetime, date, timedelta

def wishlist(request):
    currentUser = User.objects.GetCurrentUser(request)
    items = Items.objects.all()
    addedwishes = AddedWish.objects.all()
    myitemsarr = []
    otheritemsarr = []
    for item in items:
        if currentUser.name == item.user.name:
            myitemsarr.append(item)
        else:
            otheritemsarr.append(item)
    for addedwish in addedwishes:
        print "name ",addedwish.item.user.name
        if addedwish.name == currentUser.name:
            idx = 0
            while idx < len(otheritemsarr):
            #print otheritemsarr[idx].quote
                if addedwish.item == otheritemsarr[idx]:
                    print 1
                    myitemsarr.append(addedwish.item)
                    del otheritemsarr[idx]
                    idx += 1
                else:
                    print 6
                    idx +=1
    context = {
    "currentUser": currentUser,
    "myitemsarr": myitemsarr,
    "otheritemsarr": otheritemsarr
    }
    return render(request, 'project/wishlist.html', context)

def logout(request):
    return render(request, 'logreg/index.html')

def additem(request):
    currentUser = User.objects.GetCurrentUser(request)
    context = {
    "currentUser": currentUser,
    }
    return render(request, 'project/additem.html',context)

def itemadded(request,id):
    itemadded = Items.objects.itemadded(request.POST,id)
    if itemadded == True:
        print "True"
        print "user.id ",request.session['id']
        return redirect('project:wishlist')
    else:
        print "else"
        #if itemadded == False:
        for error in itemadded[1]:
            messages.error(request, error)
        return redirect('project:additem')

def delete(reuqest,id):
    delete = Items.objects.deleteList(id)
    return redirect('project:wishlist')

def remove(request,id):
    remove = Items.objects.removeList(request,id)
    return redirect('project:wishlist')

def iteminfo(request,id):
    item = Items.objects.get(id=id)
    context = {
    "item": item,
    }
    return render(request, 'project/iteminfo.html',context)

def add2wish(request,id):
    addwish = AddedWish.objects.addWish(request,id)
    return redirect('project:wishlist')

lastproject/apps/project/templates/project/additem.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Item</title>
  </head>
  <body>
    <a href="{% url 'project:wishlist' %}">Home</a>
    <br>
    <a href="{% url 'project:logout' %}">Log Out</a>
    <br>
    <br>
    <br>
    <h1>Create New Wish List Item</h1>
    <form action='{% url 'project:itemadded' currentUser.id %}' method='POST'>
      {% csrf_token %}
      Item/Product:<input type="text" name="item">
      <br>
      <input type="submit" value="Add">
    </form>
    <br>
    <br>
    {% for message in messages %}
    {{message.message}}<br>
    {% endfor %}
  </body>
</html>

lastproject/apps/project/templates/project/iteminfo.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Item Info</title>
  </head>
  <body>
    <a href="{% url 'project:wishlist' %}">Home</a>
    <br>
    <a href="{% url 'project:logout' %}">Log Out</a>
    <br>
    <br>
    <br>
    <h1>{{item.item}}</h1>
    <br>
    <br>
    Users who added this product/item under their wish list:
    <br>
    {% for addedwish in item.the_item.all %}
    {{addedwish.name}}<br>
    {% endfor %}
  </body>
</html>

lastproject/apps/project/templates/project/wishlist.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Wish List</title>
  </head>
  <body>
    Hello, {{currentUser.name}}!
    <br>
    <a href="{% url 'project:logout' %}">Log Out</a>
    <br>
    <br>
    <h1>Your Wish List</h1>
    <table>
      <tr>
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
        {% for item in myitemsarr %}
      <tr>
        <td><a href="{% url 'project:iteminfo' item.id %}">{{ item.item }}</a></td>
        <td>{{ item.user.name }} </td>
        <td>{{ item.created_at }} </td>
        <td>
          {% if item.user.name == currentUser.name %}
          <a href="{% url 'project:delete' item.id %}">Delete</a>
          {% else %}
          <a href="{% url 'project:remove' item.id %}">Remove From My Wish List</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
    <br>
    <br>
    <br>
    <br>
    <h1>Other User' Wish List</h1>
    <table>
      <tr>
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
        {% for item in otheritemsarr %}
      <tr>
        <td><a href="{% url 'project:iteminfo' item.id %}">{{ item.item }}</a></td>
        <td>{{ item.user.name }} </td>
        <td>{{ item.created_at }} </td>
        <td>
          <a href="{% url 'project:add2wish' item.id %}">Add To My Wish List</a>
        </td>
      </tr>
      {% endfor %}
    </table>
    <br>
    <br>
    <a href="{% url 'project:additem' %}">Add Item</a>
  </body>
</html>